nixpkcs.sh: Fix issues with OpenSC 0.26
We can't pipe certificate DER to OpenSC as of 0.26, since we get the
following error:

> error: Couldn't set file position to the end of the file "/dev/stdin"

Create and use a tempfile instead.